import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { LayoutGrid, ArrowRight, ArrowUpRight, Monitor, Map, Users, Bell, BarChart3, Handshake, ShieldCheck, Activity, RefreshCw, Radio, FileDown, LockKeyhole, Check, ChevronRight, Sun, Moon, Menu, X, Plus, Building2, Zap, Globe, Mail, MessageCircle, Eye, Heart, UserRoundCheck, Headphones, UserRound, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Toaster } from 'sonner';
import { ProductMock, FloorMap, StatusLegend } from '@/components/officeops/product-mock';
import { ContactForm } from '@/components/officeops/contact-form';
import officeImage from '@/assets/office.jpg';
import logoBadge from '@/assets/officeops-logo-badge.png.asset.json';
import { ProductTour } from '@/components/officeops/product-tour';
export const Route = createFileRoute('/')({
 head:()=>({meta:[{title:'OfficeOps RMM — See your whole office, live. | G&G Tech Kenya'},{name:'description',content:'Live workstation monitoring, interactive floor maps, people management and consent-first remote assistance. Explore OfficeOps RMM plans from KES 9,900/month.'},{property:'og:title',content:'OfficeOps RMM — See your whole office, live.'},{property:'og:description',content:'One live view of your office and call center. Built by G&G Tech, Kenya, with privacy at the core. Plans from KES 9,900/month.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),
 component:Index,
});
const links = [['Features','features'],['Floor Maps','floor-maps'],['Privacy','privacy'],['Pricing','pricing'],['Contact','contact']];
const features = [
 {Icon:Monitor,title:'Real-time monitoring',description:'Know what’s happening at every desk. See devices, logins, active calls, idle time and offline workstations in one live view.',tag:'One view. Every workstation.'},
 {Icon:Map,title:'Interactive floor maps',description:'Go from branch to floor, department to seat. Build your layout with drag-and-drop or auto-arrange, then watch it come alive.',tag:'Your office, at a glance.'},
 {Icon:Users,title:'People CRM',description:'Keep shifts, seat assignments and performance history together. Connect your people with the workstations they use.',tag:'People, not just devices.'},
 {Icon:Bell,title:'Alerts & announcements',description:'Catch idle desks, offline devices, late logins and no-call stretches. Share targeted updates, attachments and quick links.',tag:'The right message. The right team.'},
 {Icon:BarChart3,title:'Reports that drive action',description:'Track attendance, mic activity, idle time and shift productivity. Compare departments and export reports and alert history.',tag:'CSV, Excel & PDF exports.'},
 {Icon:Handshake,title:'Consent-based remote assist',description:'Help with a one-time 8-character code that expires in 10 minutes. User-present, view-only screen sharing in the browser.',tag:'Support with permission.'},
 {Icon:ShieldCheck,title:'Compliance controls',description:'Manage consent, microphone settings, desktop alerts and data retention. Give your team visibility into how monitoring works.',tag:'Trust built into every setting.'},
 {Icon:Activity,title:'Lightweight workstation agent',description:'A visible tray app reports boot, network, login, idle, call and mic-state telemetry. A reliable heartbeat, every 30 seconds.',tag:'Always visible. Never hidden.'},
];
const plans = [
 {name:'Starter',Icon:Zap,description:'A clear view for a growing office.',price:'9,900',capacity:'Up to 25 workstations · 1 branch',features:['Command Center & live floor maps','Inactivity & offline alerts','CSV report exports','1 admin account','Email support']},
 {name:'Business',Icon:Building2,description:'Keep people, teams and branches in sync.',price:'29,900',capacity:'Up to 150 workstations · 3 branches',features:['Everything in Starter','People CRM & shift management','Announcements & quick links','Excel & PDF reports','Consent-based remote assist','Supervisor & HR roles, scoped access','WhatsApp support']},
 {name:'Enterprise',Icon:Globe,description:'Built around your operation.',price:'Custom',capacity:'Unlimited workstations & branches',features:['Everything in Business','Compliance & retention controls','Audit log review','Self-host or cloud deployment','Custom onboarding','Priority support']},
];
const comparison = [
 ['Workstations','25','150','Unlimited'],['Branches','1','3','Unlimited'],['Command Center & live floor maps',true,true,true],['Alerts & CSV exports',true,true,true],['People CRM & announcements',false,true,true],['Excel / PDF reports & remote assist',false,true,true],['Access roles','1 admin','Admin, Supervisor, HR','Custom-scoped roles'],['Compliance, retention & audit review',false,false,true],['Deployment','Cloud','Cloud','Self-host or cloud'],['Support','Email','WhatsApp','Priority'],
];
const faqs = [
 ['What do I need to get started?','Enroll your workstations with a department code using the visible OfficeOps agent, map your seats, and open the web-based Command Center. We can walk you through your office setup in a demo.'],
 ['Does OfficeOps record calls or microphone audio?','No. OfficeOps only collects microphone state transitions and durations. It never records or stores audio. The workstation agent runs visibly, and monitoring is consent-first.'],
 ['How does remote assistance work?','The person at the workstation shares a one-time 8-character code. It expires after 10 minutes. Screen sharing is user-present and view-only; screen media travels peer-to-peer and never passes through the API. Remote assist is included in Business and Enterprise.'],
 ['Can I monitor multiple branches?','Yes. Starter includes 1 branch, Business includes 3, and Enterprise supports unlimited branches. Floor maps are organised by branch, floor, department and seat.'],
 ['Can supervisors see everyone’s information?','No. Supervisor access is department-scoped, while HR has people-only access. Business and Enterprise support these roles, so each team member sees only what their role permits.'],
 ['Can we host OfficeOps ourselves?','Yes. Enterprise offers self-hosted or cloud deployment, with custom onboarding and compliance and retention controls. Contact sales to discuss your requirements.'],
];
function Brand() {return <a href="#" className="brand" aria-label="OfficeOps RMM home"><span className="brand-mark"><img src={logoBadge.url} alt="" width={40} height={40}/></span><div><div className="brand-name">OfficeOps<small>RMM</small></div><div className="brand-by">BY G&G TECH · KENYA</div></div></a>;}
function Index() {
 const [dark,setDark]=useState(false); const [menu,setMenu]=useState(false); const [selectedPlan,setSelectedPlan]=useState('Not sure yet');
 useEffect(()=>{const saved=localStorage.getItem('officeops-theme'); setDark(saved === 'dark');},[]);
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);},[dark]);
 function toggleTheme(){setDark(v=>{localStorage.setItem('officeops-theme',v?'light':'dark'); return !v;});}
 return <><Toaster position="bottom-right" richColors/><header className="site-nav"><div className="container nav-inner"><Brand/><nav aria-label="Main navigation" className={`nav-links ${menu?'is-open':''}`}>{links.map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}</nav><div className="nav-actions"><Button variant="ghost" size="icon" aria-label={dark?'Switch to light mode':'Switch to dark mode'} title={dark?'Light mode':'Dark mode'} onClick={toggleTheme}>{dark?<Sun size={17}/>:<Moon size={17}/>}</Button><Button asChild className="nav-demo"><a href="#contact">Book a demo <ArrowUpRight size={14}/></a></Button><Button variant="ghost" size="icon" className="mobile-menu" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</Button></div></div></header>
 <main><section className="hero"><div className="container"><div className="hero-grid"><div className="hero-copy reveal"><div className="eyebrow eyebrow-pill"><i className="live-dot"/> YOUR WORKSPACE. CONNECTED. VISIBLE. LIVE.</div><h1>See your whole<br/>office, <span>live.</span></h1><p>One live view of which workstations are on, who’s logged in, on a call, idle or offline. Keep your teams connected with communication, reporting and consent-based remote assist.</p><div className="hero-buttons"><Button asChild><a href="#contact">Book a demo <ArrowUpRight/></a></Button><Button variant="outline" asChild className="hero-outline"><a href="#pricing">See pricing <ArrowRight/></a></Button></div><div className="hero-note"><ShieldCheck/> Built for visibility. Designed around trust.</div><div className="works-with"><Monitor size={14}/><span><strong>Works with</strong> a visible Windows workstation agent<br/>and a supervisor launcher.</span></div></div><ProductMock/></div><div className="hero-bottom"><strong>A clearer picture. A better-run office.</strong><span className="divider"/><StatusLegend/><span className="ml-auto">Built in Kenya. Ready for your team.</span></div></div></section>
 <section className="trust-strip" aria-label="Platform essentials"><div className="container trust-inner">{[{Icon:RefreshCw,title:'15-second live refresh',sub:'A real-time pulse of your office'},{Icon:Radio,title:'30-second heartbeats',sub:'Reliable workstation telemetry'},{Icon:FileDown,title:'CSV, Excel & PDF exports',sub:'Insights you can share and act on'},{Icon:LockKeyhole,title:'Role-based access',sub:'The right visibility for every role'}].map(({Icon,title,sub})=><div className="trust-item" key={title}><Icon/><div><strong>{title}</strong><small>{sub}</small></div></div>)}</div></section>
 <section id="features" className="section container scroll-reveal"><div className="heading-row"><div className="section-heading"><div className="eyebrow">ONE PLATFORM. A COMPLETE PICTURE.</div><h2>Less guesswork.<br/>More operational clarity.</h2><p>Everything you need to understand your office, support your people,<br className="hidden md:block"/> and keep work moving — without switching between tools.</p></div><a href="#contact" className="section-link">Explore OfficeOps in a demo <ArrowRight size={15}/></a></div><div className="features-grid">{features.map(({Icon,title,description,tag})=><article key={title} className="feature-card"><div className="feature-icon"><Icon/></div><h3>{title}</h3><p>{description}</p><div className="feature-tag"><CheckCircle2 size={11}/>{tag}</div></article>)}</div></section>
 <ProductTour/>
 <section id="floor-maps" className="section floor-section"><div className="container floor-layout scroll-reveal"><FloorMap large/><div><div className="section-heading"><div className="eyebrow">YOUR FLOOR PLAN, BROUGHT TO LIFE</div><h2>Every branch.<br/>Every seat. One live map.</h2><p>See the whole operation, then zoom into the details. A familiar view of your office makes the next action obvious.</p></div><ul className="list-check">{['Navigate branch → floor → department → seat','Arrange seats with drag-and-drop or auto-arrange','Spot logged-in, on-call, idle and offline desks instantly'].map(v=><li key={v}><Check/>{v}</li>)}</ul><a className="section-link" href="#contact">See your office on the map <ArrowRight size={15}/></a></div></div></section>
 <section className="section container scroll-reveal"><div className="section-heading center"><div className="eyebrow">FROM SETUP TO INSIGHT</div><h2>Your office, connected in three steps.</h2><p>A simple start. A live view. A more informed way to work.</p></div><div className="steps">{[{title:'Enroll your workstations',text:'Install the visible workstation agent and connect each device with its department code.'},{title:'Watch your floor come alive',text:'Place devices on your floor maps and see workstation and team statuses update live.'},{title:'Report, connect & act',text:'Turn activity into useful reports, send targeted announcements and offer consent-based support.'}].map((s,i)=><article className="step" key={s.title}><span className="step-number">0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p></article>)}</div><div className="roles">{[{Icon:ShieldCheck,title:'Admin',text:'Manage branches, devices, settings and the complete operation.'},{Icon:UserRoundCheck,title:'Supervisor',text:'Monitor and support the team within their own department.'},{Icon:UserRound,title:'HR',text:'People-only access for shifts, assignments and performance history.'}].map(({Icon,title,text})=><article className="role" key={title}><Icon/><div><h4>{title}</h4><p>{text}</p></div></article>)}</div></section>
 <section id="privacy" className="section privacy-section"><div className="container privacy-layout scroll-reveal"><div><div className="section-heading"><div className="eyebrow"><ShieldCheck size={13}/> PRIVACY ISN’T AN AFTERTHOUGHT</div><h2>Understand your office.<br/>Respect your people.</h2><p>Operational visibility should build trust, not erode it. OfficeOps keeps consent and transparency at the center.</p></div><ul className="list-check">{['Consent-first monitoring, with visible workstation agents.','Microphone state transitions and durations only — never audio.','Peer-to-peer screen sharing. Screen media never passes through the API.','Automatic data retention and audit logs for accountability.'].map(v=><li key={v}><Check/>{v}</li>)}</ul><div className="privacy-statement"><Eye/> Not hidden surveillance. Agents run visibly. Always.</div></div><div><img className="privacy-image" src={officeImage} alt="Kenyan professionals working together in a modern, open call-center office" width={1536} height={1024} loading="lazy"/><div className="privacy-caption"><Heart/> Better visibility. Stronger teams. Mutual trust.</div></div></div></section>
 <section id="pricing" className="section container scroll-reveal"><div className="section-heading center"><div className="eyebrow">A PLAN FOR EVERY OPERATION</div><h2>Clear pricing. Room to grow.</h2><p>Start with the visibility you need. Add capabilities as your team grows.<br/>Monthly subscriptions in Kenyan shillings.</p></div><div className="pricing-grid">{plans.map(p=><article className={`price-card ${p.name==='Business'?'popular':''}`} key={p.name}>{p.name==='Business'&&<span className="popular-label">MOST POPULAR</span>}<div className="plan-title"><p.Icon/>{p.name}</div><p className="plan-description">{p.description}</p><div className="price">{p.price!=='Custom'&&<sup>KES</sup>}{p.price}{p.price!=='Custom'&&<small> / month</small>}</div><p className="plan-capacity">{p.capacity}</p><Button asChild variant={p.name==='Business'?'default':'outline'}><a href="#contact" onClick={()=>setSelectedPlan(p.name)}>{p.name==='Enterprise'?'Contact sales':'Book a demo'}<ArrowUpRight/></a></Button><ul className="list-check">{p.features.map(f=><li key={f}><Check/>{f}</li>)}</ul></article>)}</div><div className="comparison"><table><caption className="sr-only">OfficeOps monthly plan feature comparison</caption><thead><tr><th scope="col">Compare plans</th>{plans.map(p=><th scope="col" key={p.name}>{p.name}</th>)}</tr></thead><tbody>{comparison.map(([label,...values])=><tr key={String(label)}><td>{label}</td>{values.map((v,i)=><td key={i}>{typeof v==='boolean' ? v ? <><Check aria-hidden="true"/><span className="sr-only">Included</span></> : <span aria-label="Not included">—</span> : v}</td>)}</tr>)}</tbody></table></div><div className="faq"><h3>A few things you might be wondering.</h3>{faqs.map(([question,answer])=><details key={question}><summary>{question}<Plus/></summary><p>{answer}</p></details>)}</div></section>
 <section id="contact" className="section contact-section"><div className="container contact-layout scroll-reveal"><div><div className="section-heading"><div className="eyebrow">LET’S MAKE WORK MORE VISIBLE</div><h2>Meet your new<br/>command center.</h2><p>Tell us about your team. We’ll show you how OfficeOps can bring your office into focus.</p></div><div className="contact-card"><MessageCircle/><div><h3>Prefer a conversation?</h3><p>WhatsApp · +254 7XX XXX XXX</p></div><ArrowUpRight size={16} className="ml-auto text-muted-foreground"/></div><div className="contact-card"><Mail/><div><h3>Send us an email</h3><p>hello@ggtech.example</p></div><ArrowUpRight size={16} className="ml-auto text-muted-foreground"/></div><p className="contact-placeholder">Contact details are placeholders. Official details coming soon.</p></div><ContactForm selectedPlan={selectedPlan}/></div></section>
 </main><footer><div className="container"><div className="footer-top"><Brand/><div className="footer-links">{links.map(([label,id])=><a key={id} href={`#${id}`}>{label}</a>)}</div></div><div className="footer-bottom"><span>© 2026 G&G Tech. All rights reserved.</span><span><Globe size={12}/> Built in Kenya. Built for better operations.</span></div></div></footer></>;
}
