import { Check, Monitor, Map, Users, Bell, BarChart3, ShieldCheck, UserRound, Activity, LockKeyhole } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { BrowserFrame } from './browser-frame';
import command from '@/assets/screens/command-center.webp.asset.json';
import activity from '@/assets/screens/activity-feed.webp.asset.json';
import departments from '@/assets/screens/departments.webp.asset.json';
import people from '@/assets/screens/people-crm.webp.asset.json';
import alerts from '@/assets/screens/alerts-comms.webp.asset.json';
import reports from '@/assets/screens/reports.webp.asset.json';
import compliance from '@/assets/screens/compliance.webp.asset.json';
import security from '@/assets/screens/profile-security.webp.asset.json';
import login from '@/assets/screens/login.webp.asset.json';

const screens = [
  { id: 'command', tab: 'Command Center', Icon: Monitor, asset: command, heading: 'One live pulse of your whole workspace.', description: 'See Live Devices, On Active Call, Idle Desks and Offline Machines together. Today’s Call Time includes utilization, while Today’s Online Time shows idle time alongside a 7-day Productivity Trend.', points: ['Live Device Activity: foreground app, browser domain, microphone state and duration', 'No titles, content, audio or full URLs are collected', 'Filter device activity by department', 'Call, online and idle minutes across the last 7 days'], alt: 'OfficeOps Command Center with live device, call, idle and offline counts, daily time totals, department filter and productivity chart' },
  { id: 'activity', tab: 'Activity feed', Icon: Activity, asset: activity, heading: 'Your most active people, at a glance.', description: 'The Top Active Employees list brings today’s call activity and workstation uptime together. Each person appears with their department, call time and current status badge.', points: ['Top Active Employees with department names', 'Logged In, Break and Connected status badges', 'On Call and Offline states', 'Call-time totals beside each employee'], alt: 'OfficeOps Top Active Employees list showing departments, call-time totals and Logged In, Break, Connected, On Call and Offline badges' },
  { id: 'departments', tab: 'Departments', Icon: Map, asset: departments, heading: 'Real-time department floor plans.', description: 'Create departments and choose a floor colour for each room. Move devices into the right room, then drag each workstation into position.', points: ['Create named departments', 'Choose a floor colour', 'Move devices to the appropriate room', 'Drag workstations into position'], alt: 'OfficeOps Departments screen with a new department field, floor colour picker and real-time department floor plan area' },
  { id: 'people', tab: 'People CRM', Icon: Users, asset: people, heading: 'Profiles for employees and supervisors.', description: 'Create profiles and link or assign devices to the people who use them. Keep contact details, device credentials and notes together, with an Employee Directory.', points: ['Employee and Supervisor profile options', 'Link existing devices or create device credentials', 'Store email, phone and notes', 'Employee Directory'], alt: 'OfficeOps People CRM profile form with employee and supervisor options, device assignment, email, phone, device credentials and notes' },
  { id: 'alerts', tab: 'Alerts & Comms', Icon: Bell, asset: alerts, heading: 'Reach every desk.', description: 'Broadcast announcements to all devices or a single department with Normal or higher priority. Add downloadable attachments and department Quick Links, so devices only see links for their own department.', points: ['Broadcast titles and messages', 'All-device or department targeting', 'Priority selection and downloadable attachments', 'Department-specific Quick Links'], alt: 'OfficeOps Alerts and Comms broadcast form with title, message, file attachments, audience, priority and department Quick Links' },
  { id: 'reports', tab: 'Reports', Icon: BarChart3, asset: reports, heading: 'Attendance and department comparison.', description: 'Use trend charts to compare staffing and department productivity. Recent attendance shows login and logout times reported from each machine’s clock, with CSV exports for the activity you need to review.', points: ['Attendance and department trend charts', 'Recent attendance from each machine’s clock', 'Attendance, mic-activity and idle-time CSV exports', 'Shift-productivity and department-comparison CSV exports'], alt: 'OfficeOps Reports screen showing attendance comparison chart, recent attendance totals and CSV export categories' },
  { id: 'compliance', tab: 'Compliance', Icon: ShieldCheck, asset: compliance, heading: 'Consent and monitoring controls.', description: 'Require employee consent and choose which monitoring signals are enabled. Set activity and audit retention days, with controls for desktop alerts from admin broadcasts.', points: ['Require consent before activity monitoring', 'Optional foreground app names and activity duration', 'Browser domains only — never full URLs or page titles', 'Microphone-in-use state without recording audio'], alt: 'OfficeOps Compliance controls for employee consent, app and domain tracking, microphone state, desktop alerts and activity and audit retention days' },
  { id: 'security', tab: 'Account security', Icon: UserRound, asset: security, heading: 'Profile and security.', description: 'Keep your account identity and protection settings together. Manage profile information, login protection and password changes, then review recent security activity or revoke all sessions.', points: ['Profile information', 'Login protection and password changes', 'Recent security activity', 'Revoke all sessions'], alt: 'OfficeOps Profile and Security screen with account details and navigation for login protection, password changes, security activity and session revocation' },
];

export function ProductTour() {
  return <section id="real-product" className="section product-tour-section"><div className="container">
    <div className="section-heading"><div className="eyebrow">INSIDE OFFICEOPS RMM</div><h2>See the real product</h2><p>A closer look at your workspace, people and operational controls.</p></div>
    <article className="login-preview"><div><div className="tour-kicker"><LockKeyhole size={15}/> ADMIN COMMAND CENTER</div><h3>Secure access. Visible consent.</h3><p>Admin Command Center: secure cloud access, with remote sessions requiring an expiring code and visible consent.</p></div><BrowserFrame src={login.url} label="OfficeOps RMM · Secure sign-in" alt="OfficeOps Admin Command Center login screen with username, password and a protected workspace notice requiring an expiring remote-session code and visible consent"/></article>
    <Tabs defaultValue="command" className="product-tour"><TabsList className="tour-tabs" aria-label="Real product screens">{screens.map(({ id, tab, Icon }) => <TabsTrigger value={id} key={id} className="tour-tab"><Icon size={15}/>{tab}</TabsTrigger>)}</TabsList>
      {screens.map(screen => <TabsContent value={screen.id} key={screen.id} className="tour-content"><div className="tour-copy"><div className="tour-kicker"><screen.Icon size={16}/>{screen.tab}</div><h3>{screen.heading}</h3><p>{screen.description}</p><ul className="list-check">{screen.points.map(point => <li key={point}><Check aria-hidden="true"/>{point}</li>)}</ul></div><BrowserFrame src={screen.asset.url} alt={screen.alt} label={`OfficeOps RMM · ${screen.tab}`}/></TabsContent>)}
    </Tabs>
  </div></section>;
}